# app - simple test app

driver:
  skopos:
    model: app-model.yaml
    teds:
      - app-env.yaml
    force_replace: False

components:

  back:
     settings:
        cpu: { type: range, min: 0.1, max: 1, value: 0.5 }
        #mem: { min: 1, max: 100, value: 20 }
        #back_work: { min: 1, max: 100, value: 20 }

  front:
     settings:
        cpu: { type: range, min: 0.1, max: 1, value: 0.5 }
        #mem: { min: 1, max: 100, value: 40 }
        #front_work: { min: 1, max: 100, value: 20 }
